https-portal:
  image: steveltn/https-portal:1.0.0
  ports:
    # - '80:80'
    - '443:443'
  links:
    - chat
  restart: always
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
  environment:
    DOMAINS: 'nodetest.com -> http://chat:3000'
    STAGE: local
    # FORCE_RENEW: 'true'
chat:
  build: .
  # ports:
  #   - '3000:3000'
  volumes:
    - .:/home/app/chat
    - /home/app/chat/node_modules