version: '2'

services:
  nginx:
    build: nginx
    ports:
      - '80:80'
      - '443:443'
    links:
      # - chat
      - php7
    restart: always
    environment:
      # DOMAINS: 'nodetest.com -> http://chat:3000'
      DOMAINS: 'nodetest2.com -> http://php7:9000'
      STAGE: local
      # FORCE_RENEW: 'true'
  # chat:
  #   build: node
  #   volumes:
  #     - .:/home/app/chat
  #     - /home/app/chat/node_modules
  php7:
    build: ./php7
    volumes: 
      - .:/var/www/html/