version: '2'

services:
  composer:
    build: docker/composer
    volumes:
      - ./applications/laravel:/home/app/laravel
    command: ["composer", "install"]
    container_name: composer
  nginx:
    build: docker/nginx
    ports:
      - '80:80'
      - '443:443'
    links:
      - node
      - app
    restart: always
    container_name: nginx
  node:
    build: docker/node
    volumes:
      - ./applications/node:/home/app/node
      - /home/app/node/node_modules
    command: ["npm", "install"]
    command: ["npm", "cache", "clean"]
    command: ["node", "index.js"]
    container_name: node
  app:
    build: docker/php-fpm
    links:
      - mysql
      - redis
    environment:
      DB_HOST: 'mysql'
      DB_NAME: 'rydberg'
      DB_USER: 'rydberg'
      DB_PASS: 'v8kYAbpAYPJz'
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./applications/laravel/:/var/www/html/laravel
    container_name: app
  data:
    image: busybox
    volumes:
      - ./docker/misc/data:/var/lib/mysql
    container_name: data
  mysql:
    build: docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rydberg
      MYSQL_USER: rydberg
      MYSQL_PASSWORD: v8kYAbpAYPJz
    ports:
      - "13306:3306"
    volumes_from:
      - data
    container_name: mysql
  redis:
    build: docker/redis
    links:
      - node
    container_name: redis