version: '2'

services:
  nginx:
    build: nginx
    ports:
      - '80:80'
      - '443:443'
    links:
      - chat
      - app
    restart: always
    environment:
      DOMAINS: 'nodetest.com -> http://chat:3000'
      STAGE: local
      # FORCE_RENEW: 'true'
  chat:
    build: node
    volumes:
      - .:/home/app/chat
      - /home/app/chat/node_modules
  app:
    build: php-fpm
    links:
      - mysql
      - redis
    environment:
      DB_HOST: 'mysql'
      DB_NAME: 'rydberg'
      DB_USER: 'rydberg'
      DB_PASS: 'v8kYAbpAYPJz'
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./src:/var/www/html
  data:
    image: busybox
    volumes:
      - ./misc/data:/var/lib/mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rydberg
      MYSQL_USER: rydberg
      MYSQL_PASSWORD: v8kYAbpAYPJz
    ports:
      - "13306:3306"
    volumes_from:
      - data
  redis:
    build: redis
    links:
      - chat
